name: 'Build and Deploy Webpage'
on:
  push:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Setup ğŸ›ï¸'
        uses: 'dudeofawesome/actions/node-setup@v1'
      - name: 'Build ğŸ—'
        run: 'NODE_ENV=production npm run build'

  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Setup ğŸ›ï¸'
        uses: 'dudeofawesome/actions/node-setup@v1'
      - name: 'Lint ğŸš¨'
        run: 'npm run lint'

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Setup ğŸ›ï¸'
        uses: 'dudeofawesome/actions/node-setup@v1'
      - name: 'Test ğŸ§ª'
        run: 'npm run test'

  export:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    needs:
      - 'build'
    steps:
      - name: 'Install Chrome â•'
        uses: 'browser-actions/setup-chrome@latest'
      - name: 'Setup ğŸ›ï¸'
        uses: 'dudeofawesome/actions/node-setup@v1'

      - name: 'Build ğŸ—'
        run: 'NODE_ENV=production npm run build'
      - name: 'Render PDF ğŸ–¨ï¸'
        run: 'npm run render-pdf'
      - name: 'Export ğŸ§±'
        run: 'npm run export'

      - name: 'Add nojekyll file ğŸ’©'
        run: 'touch "out/.nojekyll"' # fixes missing style

      - name: 'Upload artifact ğŸ§©'
        uses: 'actions/upload-pages-artifact@v1'
        with:
          path: './out'

  deploy:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-latest'
    needs:
      - 'lint'
      - 'test'
      - 'export'
    if: '(github.ref_name == github.event.repository.default_branch)'
    permissions:
      pages: 'write'
      id-token: 'write'
    steps:
      - name: 'Deploy to GitHub Pages ğŸš€'
        id: 'deployment'
        uses: 'actions/deploy-pages@v1'
